
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fujitsu
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int operator;
        do {
            String text = JOptionPane.showInputDialog(null, "1=Addition \n"
                    + "2=Substraction   \n "
                    + "3=Multiplication \n "
                    + "4=Division   \n"
                    + "5=Pow   \n"
                    + "6=Sinx   \n"
                    + "7=Cosx   \n"
                    + "8=Log    \n"
                    + "Or Press -1 to exit  \n");
            operator = Integer.parseInt(text);

            switch (operator) {
                case 1:
                    System.out.println("Addition  ");
                    String add1 = JOptionPane.showInputDialog(null, "Enter first number ");
                    System.out.print("X= ");
                    double addnumber1 = Integer.parseInt(add1);
                    System.out.println(addnumber1);
                    String add2 = JOptionPane.showInputDialog(null, "Enter second number ");
                    System.out.print("Y= ");
                    double addnumber2 = Integer.parseInt(add2);
                    System.out.println(addnumber1);
                    double Sum = addnumber1 + addnumber2;
                    System.out.print("Sum =  ");
                    JOptionPane.showMessageDialog(null, Sum, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println(Sum);
                    System.out.println();
                    break;
                case 2:
                    System.out.println("Substraction  ");
                    String sub1 = JOptionPane.showInputDialog(null, "Enter first number ");
                    System.out.print("X= ");
                    double subnumber1 = Integer.parseInt(sub1);
                    System.out.println(subnumber1);
                    String sub2 = JOptionPane.showInputDialog(null, "Enter second number ");
                    System.out.print("Y= ");
                    double subnumber2 = Integer.parseInt(sub2);
                    System.out.print("Sub =  ");
                    double Sub = subnumber1 - subnumber2;
                    JOptionPane.showMessageDialog(null, Sub, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println(Sub);
                    System.out.println();
                    break;

                case 3:
                     System.out.println("Multiplication  ");
                    String mul1 = JOptionPane.showInputDialog(null, "Enter first number ");
                    System.out.print("X= ");
                    double mulnumber1 = Integer.parseInt(mul1);
                    System.out.println(mulnumber1);
                    String mul2 = JOptionPane.showInputDialog(null, "Enter second number ");
                    System.out.print("Y= ");
                    double mulnumber2 = Integer.parseInt(mul2);
                    System.out.println(mulnumber2);
                    double mul = mulnumber1 * mulnumber2;
                    System.out.print("Mul =");
                    JOptionPane.showMessageDialog(null, mul, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println(mul);
                    System.out.println();
                    break;
                case 4:
                    System.out.println("Division  ");
                    String div1 = JOptionPane.showInputDialog(null, "Enter first number ");
                    System.out.print("X= ");
                    double divNumber1 = Integer.parseInt(div1);
                    System.out.println(divNumber1);
                    String div2 = JOptionPane.showInputDialog(null, "Enter second number ");
                    System.out.print("X= ");
                    double divNumber2 = Integer.parseInt(div2);
                    System.out.println(divNumber2);
                    if (divNumber2 == 0) {
                        JOptionPane.showMessageDialog(null, "Devision by 0 can not be done ");
                        System.out.println("Devision by 0 can not be done");
                    }
                    System.out.print("Div =");
                    double div = divNumber1 / divNumber2;

                    JOptionPane.showMessageDialog(null, div, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println(div);
                    System.out.println();

                    break;

                case 5:
                    System.out.println("X pow y (X^y) ");
                    String pow1 = JOptionPane.showInputDialog(null, "Enter first number ");
                    System.out.print("X= ");
                    double powNumber1 = Integer.parseInt(pow1);
                    System.out.println(powNumber1);
                    String pow2 = JOptionPane.showInputDialog(null, "Enter second number ");
                    System.out.print("y= ");

                    double powNumber2 = Integer.parseInt(pow2);
                    System.out.println(powNumber2);
                    System.out.print("Pow =");
                    double pow = Math.pow(powNumber1, powNumber2);
                    JOptionPane.showMessageDialog(null, pow, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println(pow);
                    System.out.println();
                    break;
                case 6:
                   System.out.println("Find Sinx  ");
                    String sin1 = JOptionPane.showInputDialog(null, "Enter One Number ");
                    
                    System.out.print("x = ");
                    double sinnumber1 = Integer.parseInt(sin1);
                    System.out.println(sinnumber1);
                    double sin = Math.sin(sinnumber1);
                    JOptionPane.showMessageDialog(null, sin, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println("Sinx =");
                    System.out.print(sin);
                    System.out.println();
                    break;
                case 7:
                     System.out.println("Find Cosx  ");
                    String cos1 = JOptionPane.showInputDialog(null, "Enter One Number ");
                   
                    System.out.print("x = ");
                    double cosnumber1 = Integer.parseInt(cos1);
                    System.out.println(cosnumber1);
                    double cos = Math.cos(cosnumber1);
                    JOptionPane.showMessageDialog(null, cos, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println("Cosx =");
                    System.out.print(cos);
                    System.out.println();
                    break;
                case 8:
                    System.out.println("Find LogA  ");
                    String log1 = JOptionPane.showInputDialog(null, "Enter base : ");

                    System.out.print(" Base of Log =");
                    double lognumber1 = Integer.parseInt(log1);
                    System.out.println(lognumber1);
                    if (lognumber1 <= 0) {
                        JOptionPane.showMessageDialog(null, "Logb(x) is Undefind for x<=0");
                    }
                    String log2 = JOptionPane.showInputDialog(null, "Enter number : ");
                    System.out.print(" A =");
                    double lognumber2 = Integer.parseInt(log2);
                    System.out.println(lognumber2);
                    if (lognumber2 <= 0) {
                        JOptionPane.showMessageDialog(null, " Please enter a positive number");
                        System.out.println("Please enter a positive number");
                    }
                    double log = (Math.log(lognumber2) / Math.log(lognumber1));
                    JOptionPane.showMessageDialog(null, log, "Result =", JOptionPane.PLAIN_MESSAGE);
                    System.out.println("LogA =");
                    System.out.print(log);
                    System.out.println();

                    break;
                case -1:
                default:
            }

        } while (operator != (-1));

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}
